name: CD Pipeline (Self-Hosted)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest Docker image
        shell: pwsh
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      - name: Stop existing container
        shell: pwsh
        run: |
          try {
            docker stop myapp
          } catch {
            echo "No running container"
          }

      - name: Remove existing container
        shell: pwsh
        run: |
          try {
            docker rm myapp
          } catch {
            echo "No container to remove"
          }

      - name: Run new container
        shell: pwsh
        run: |
          docker run -d -p 3000:3000 --name myapp ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      - name: Show running containers
        shell: pwsh
        run: docker ps
