name: CD Pipeline (Self-Hosted)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull latest Docker image
        shell: cmd
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      - name: Stop existing container
        shell: cmd
        run: |
          docker stop myapp || echo "No running container" & exit /B 0

      - name: Remove container
        shell: cmd
        run: |
          docker rm myapp || echo "No container to remove" & exit /B 0

      - name: Run new container
        shell: cmd
        run: docker run -d -p 3000:3000 --name myapp ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      - name: Show running containers
        shell: cmd
        run: docker ps
