name: CI - Build & Push Docker Image (Self-Hosted)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Windows] # change according to your runner labels

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      - name: Show Docker images on runner
        run: docker images
